services:
  app:
    build:
      context: .
      dockerfile: ./Dockerfile
    env_file:
      - ./config/.env
    ports:
      - '3002:3002'
    command: pnpm run start:debug
    volumes:
      - ./:/app/
      - /app/node_modules
    networks:
      - backend

networks:
  backend:
    external: true
